## Setup

`.env` must contain the following values:
```
SERVER_IP=your_server_ip
FTP_PORT=21
FTP_USER=your_username
FTP_PASSWORD=your_password
```

Use the same `.venv` you use for dev here with python >= 3.12.10

In [1]:
from ftplib import FTP
from pathlib import Path
from dotenv import load_dotenv
import os

# --- LOAD ENV ---
BASE_DIR = Path().resolve().parents[2] / "Internomat"
env_path = BASE_DIR / ".env"

load_dotenv(env_path)

# --- ENV VARS ---
FTP_HOST = os.getenv("SERVER_IP")
FTP_PORT = int(os.getenv("FTP_PORT", 21))
FTP_USER = os.getenv("FTP_USER")
FTP_PASSWORD = os.getenv("FTP_PASSWORD")

print("\n[ENV DEBUG]")
print("FTP_HOST =", FTP_HOST)
print("FTP_PORT =", FTP_PORT)
print("FTP_USER =", FTP_USER)
print("FTP_PASSWORD =", "SET" if FTP_PASSWORD else "MISSING")

# --- HARD VALIDATION ---
assert FTP_HOST, "FTP_HOST missing (check .env)"
assert FTP_USER, "FTP_USER missing (check .env)"
assert FTP_PASSWORD, "FTP_PASSWORD missing (check .env)"

# --- PATHS ---
REMOTE_DIR = "/cs2/game/csgo/MatchZy"
LOCAL_DIR = BASE_DIR / "test_demos"  

LOCAL_DIR.mkdir(parents=True, exist_ok=True)

print(f"\n[FTP] Connecting to {FTP_HOST}:{FTP_PORT}...")

# --- CONNECT ---
ftp = FTP()

try:
    ftp.connect(FTP_HOST, FTP_PORT, timeout=10)
    ftp.login(FTP_USER, FTP_PASSWORD)
    ftp.set_pasv(True) 

    print("[FTP] Connected")

    # --- NAVIGATE ---
    ftp.cwd(REMOTE_DIR)
    print(f"[FTP] Changed dir → {REMOTE_DIR}")

    files = ftp.nlst()

    downloaded = 0
    skipped = 0

    print(f"[FTP] Found {len(files)} files")

    from tqdm import tqdm

    for file in files:
        if not file.endswith(".dem"):
            continue

        local_file = LOCAL_DIR / file

        if local_file.exists():
            print(f"[SKIP] {file}")
            skipped += 1
            continue

        print(f"[DOWNLOAD] {file}")

        try:
            # --- GET FILE SIZE ---
            filesize = ftp.size(file)

            with open(local_file, "wb") as f, tqdm(
                total=filesize,
                unit="B",
                unit_scale=True,
                desc=file,
                leave=False
            ) as pbar:

                def callback(data):
                    f.write(data)
                    pbar.update(len(data))

                ftp.retrbinary(f"RETR {file}", callback)

            downloaded += 1

        except Exception as e:
            print(f"[ERROR] Failed to download {file}: {e}")

    print("\n[FTP] Done")
    print(f"Downloaded: {downloaded}")
    print(f"Skipped: {skipped}")

except Exception as e:
    print(f"\n FTP ERROR: {e}")

finally:
    try:
        ftp.quit()
    except:
        pass

[ENV DEBUG]
FTP_HOST = 83.141.26.49
FTP_PORT = 21
FTP_USER = server18681
FTP_PASSWORD = SET

[FTP] Connecting to 83.141.26.49:21...
[FTP] Connected
[FTP] Changed dir → /cs2/game/csgo/MatchZy
[FTP] Found 12 files
[SKIP] 2026-03-14_21-36-41_19_cs_alpine_team_prinoX_vs_team_Amü.dem
[SKIP] 2026-03-14_22-28-27_20_de_cache_team_KeTaNoS_vs_team_Tundra_ツ.dem
[DOWNLOAD] 2026-03-14_22-37-47_21_de_cache_team_Amü_vs_team_Tundra_ツ.dem

[DOWNLOAD] 2026-03-14_23-34-54_22_de_cbble_d_team_Dude_vs_team_Sindilia.dem

[DOWNLOAD] 2026-03-15_00-20-53_23_de_dust2_team_Luffy-Eyss_vs_team_Amü.dem

[DOWNLOAD] 2026-03-18_20-41-07_24_de_cbble_d_team_kfinimpar_vs_team_Tundra_ツ.dem

[SKIP] 2026-03-18_21-50-33_25_de_overpass_team_Captain_Blake_vs_team_Dottersack.dem
[SKIP] 2026-03-19_21-10-26_-1_de_thera_team_Captain_Blake_vs_team_Tundra_ツ.dem
[SKIP] 2026-03-19_21-55-45_1_de_warden_team_Dude_vs_team_Amü.dem
[SKIP] 2026-03-20_20-40-16_2_de_thera_team_Soulcrusher_vs_team_Tundra_ツ.dem
[SKIP] 2026-03-20_21-57-48_3_de_mills_team_Sindilia_vs_team_Dottersack.dem
[SKIP] 2026-03-20_22-48-10_4_cs_office_team_TEAMsl1χχ__єχχтяємє_vs_team_Tundra_ツ.dem

[FTP] Done
Downloaded: 4
Skipped: 8

In [ ]:
from pathlib import Path
from awpy import Demo

# from LOCAL_DIR select the first .dem file
DEMO_PATH = next(LOCAL_DIR.glob("*.dem"), None)

if DEMO_PATH is None:
    raise FileNotFoundError("No .dem file found in the specified directory.")

print("Resolved path:", DEMO_PATH)
print("Exists:", DEMO_PATH.exists())


def load_demo(path: Path):
    path = path.resolve()

    if not path.exists():
        raise FileNotFoundError(f"Demo not found: {path}")

    print(f"[Demo] Loading: {path}")

    demo = Demo(path=str(path))
    demo.parse()

    print("[Demo] Parsing complete.")
    return demo

def inspect_demo_attributes(demo):
    print("\n=== AVAILABLE DEMO ATTRIBUTES ===")

    attrs = dir(demo)

    # filter useful ones
    public_attrs = [a for a in attrs if not a.startswith("_")]

    for attr in sorted(public_attrs):
        try:
            value = getattr(demo, attr)

            if isinstance(value, list):
                print(f"{attr:20} -> list ({len(value)} items)")
            elif isinstance(value, dict):
                print(f"{attr:20} -> dict ({len(value)} keys)")
            else:
                print(f"{attr:20} -> {type(value).__name__}")

        except Exception as e:
            print(f"{attr:20} -> ERROR: {e}")

demo = load_demo(DEMO_PATH)

inspect_demo_attributes(demo)

Resolved path: D:\Git_repo\Internomat\test_demos\2026-03-20_21-57-48_3_de_mills_team_Sindilia_vs_team_Dottersack.dem
Exists: True
[Demo] Loading: D:\Git_repo\Internomat\test_demos\2026-03-20_21-57-48_3_de_mills_team_Sindilia_vs_team_Dottersack.dem
[Demo] Parsing complete.

=== AVAILABLE DEMO ATTRIBUTES ===
bomb                 -> DataFrame
compress             -> method
damages              -> DataFrame
default_events       -> list (20 items)
detected_events      -> list (42 items)
events               -> dict (21 keys)
footsteps            -> DataFrame
grenades             -> DataFrame
header               -> dict (12 keys)
in_play_ticks        -> Series
inferno_duration     -> float
infernos             -> DataFrame
kills                -> DataFrame
parse                -> method
parse_events         -> method
parse_grenades       -> method
parse_header         -> method
parse_ticks          -> method
parser               -> DemoParser
path                 -> WindowsPath
player_round_totals  -> DataFrame
rounds               -> DataFrame
server_cvars         -> DataFrame
shots                -> DataFrame
smoke_duration       -> float
smokes               -> DataFrame
tickrate             -> int
ticks                -> DataFrame

In [11]:
import pandas as pd

# PARSER
def parse_demo_full(demo):
    print("\n[Demo] Building structured tables (explicit)...")

    data = {}

    # --- HEADER ---
    data["header"] = demo.header

    # --- KNOWN TABLES ---
    table_map = {
        "rounds": "rounds",
        "kills": "kills",
        "damages": "damages",
        "grenades": "grenades",
        "shots": "shots",
        "footsteps": "footsteps",
        "smokes": "smokes",
        "infernos": "infernos",
        "bomb": "bomb",
        "ticks": "ticks",
        "player_round_totals": "player_round_totals",
        "server_cvars": "server_cvars",
    }

    for key, attr in table_map.items():
        try:
            value = getattr(demo, attr, None)

            if value is None:
                print(f"[NULL] {key}")
                data[key] = None
                continue

            # force into DataFrame if possible
            if isinstance(value, pd.DataFrame):
                df = value
            elif isinstance(value, list):
                df = pd.DataFrame(value)
            else:
                df = value  

            data[key] = df

            if isinstance(df, pd.DataFrame):
                print(f"[OK]   {key:22} -> {len(df)} rows")
            else:
                print(f"[OK]   {key:22} -> {type(df).__name__}")

        except Exception as e:
            print(f"[FAIL] {key}: {e}")
            data[key] = None

    print("\n[Demo] Total collected:", len(data))

    return data


data = parse_demo_full(demo)
# print frame 
print("\n=== DEMO DATA STRUCTURE ===\n")
print (data)

[Demo] Building structured tables (explicit)...
[OK]   rounds                 -> DataFrame
[OK]   kills                  -> DataFrame
[OK]   damages                -> DataFrame
[OK]   grenades               -> DataFrame
[OK]   shots                  -> DataFrame
[OK]   footsteps              -> DataFrame
[OK]   smokes                 -> DataFrame
[OK]   infernos               -> DataFrame
[OK]   bomb                   -> DataFrame
[OK]   ticks                  -> DataFrame
[OK]   player_round_totals    -> DataFrame
[OK]   server_cvars           -> DataFrame

[Demo] Total collected: 13

=== DEMO DATA STRUCTURE ===

{'header': {'demo_version_name': 'valve_demo_2', 'server_name': 'MatchZy | team_Sindilia vs team_Dottersack', 'map_name': 'de_mills', 'fullpackets_version': '2', 'game_directory': '/home/server18681/cs2/game/csgo', 'demo_version_guid': '8e9d71ab-04a1-4c01-bb61-acfede27c046', 'demo_file_stamp': 'PBDEMS2\x00', 'client_name': 'SourceTV Demo', 'allow_clientside_entities': True, 'patch_version': '14141', 'allow_clientside_particles': True, 'addons': '3152430710'}, 'rounds': shape: (24, 9)
┌───────────┬────────┬────────────┬────────┬───┬────────┬──────────────┬────────────┬─────────────┐
│ round_num ┆ start  ┆ freeze_end ┆ end    ┆ … ┆ winner ┆ reason       ┆ bomb_plant ┆ bomb_site   │
│ ---       ┆ ---    ┆ ---        ┆ ---    ┆   ┆ ---    ┆ ---          ┆ ---        ┆ ---         │
│ u32       ┆ i32    ┆ i32        ┆ i32    ┆   ┆ str    ┆ str          ┆ i64        ┆ str         │
╞═══════════╪════════╪════════════╪════════╪═══╪════════╪══════════════╪════════════╪═════════════╡
│ 1         ┆ 6838   ┆ 7990       ┆ 9509   ┆ … ┆ ct     ┆ t_killed     ┆ null       ┆ not_planted │
│ 2         ┆ 9957   ┆ 11109      ┆ 18469  ┆ … ┆ ct     ┆ time_ran_out ┆ null       ┆ not_planted │
│ 3         ┆ 18917  ┆ 20069      ┆ 25569  ┆ … ┆ t      ┆ ct_killed    ┆ 23901      ┆ bombsite_b  │
│ 4         ┆ 26017  ┆ 27169      ┆ 33284  ┆ … ┆ t      ┆ ct_killed    ┆ 32283      ┆ bombsite_b  │
│ 5         ┆ 33732  ┆ 34884      ┆ 37373  ┆ … ┆ t      ┆ ct_killed    ┆ null       ┆ not_planted │
│ …         ┆ …      ┆ …          ┆ …      ┆ … ┆ …      ┆ …            ┆ …          ┆ …           │
│ 20        ┆ 135320 ┆ 136472     ┆ 140021 ┆ … ┆ ct     ┆ t_killed     ┆ null       ┆ not_planted │
│ 21        ┆ 140469 ┆ 141621     ┆ 145402 ┆ … ┆ t      ┆ ct_killed    ┆ null       ┆ not_planted │
│ 22        ┆ 145850 ┆ 147002     ┆ 150534 ┆ … ┆ t      ┆ ct_killed    ┆ 149169     ┆ bombsite_b  │
│ 23        ┆ 150982 ┆ 152134     ┆ 157746 ┆ … ┆ t      ┆ ct_killed    ┆ 155466     ┆ bombsite_b  │
│ 24        ┆ 158194 ┆ 159346     ┆ 162268 ┆ … ┆ t      ┆ ct_killed    ┆ 161280     ┆ bombsite_b  │
└───────────┴────────┴────────────┴────────┴───┴────────┴──────────────┴────────────┴─────────────┘, 'kills': shape: (180, 47)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ assistedfl ┆ assister_X ┆ assister_Y ┆ assister_Z ┆ … ┆ weapon_it ┆ weapon_or ┆ wipe ┆ round_num │
│ ash        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ emid      ┆ iginalown ┆ ---  ┆ ---       │
│ ---        ┆ f32        ┆ f32        ┆ f32        ┆   ┆ ---       ┆ er_xuid   ┆ i32  ┆ u32       │
│ bool       ┆            ┆            ┆            ┆   ┆ str       ┆ ---       ┆      ┆           │
│            ┆            ┆            ┆            ┆   ┆           ┆ str       ┆      ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 619575366 ┆           ┆ 0    ┆ 1         │
│            ┆            ┆            ┆            ┆   ┆ 0         ┆           ┆      ┆           │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 473833654 ┆           ┆ 0    ┆ 1         │
│            ┆            ┆            ┆            ┆   ┆ 20        ┆           ┆      ┆           │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 619575366 ┆           ┆ 0    ┆ 1         │
│            ┆            ┆            ┆            ┆   ┆ 0         ┆           ┆      ┆           │
│ false      ┆ -250.07501 ┆ -2160.6992 ┆ -87.96875  ┆ … ┆ 473833654 ┆           ┆ 0    ┆ 1         │
│            ┆ 2          ┆ 19         ┆            ┆   ┆ 20        ┆           ┆      ┆           │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 619575366 ┆           ┆ 0    ┆ 1         │
│            ┆            ┆            ┆            ┆   ┆ 0         ┆           ┆      ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …    ┆ …         │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 0         ┆           ┆ 0    ┆ 24        │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 473582244 ┆           ┆ 0    ┆ 24        │
│            ┆            ┆            ┆            ┆   ┆ 30        ┆           ┆      ┆           │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 184236743 ┆           ┆ 0    ┆ 24        │
│            ┆            ┆            ┆            ┆   ┆ 32        ┆           ┆      ┆           │
│ false      ┆ -2647.9611 ┆ -1200.2589 ┆ -31.96875  ┆ … ┆ 280821697 ┆           ┆ 0    ┆ 24        │
│            ┆ 82         ┆ 11         ┆            ┆   ┆ 98        ┆           ┆      ┆           │
│ false      ┆ null       ┆ null       ┆ null       ┆ … ┆ 280821697 ┆           ┆ 0    ┆ 24        │
│            ┆            ┆            ┆            ┆   ┆ 98        ┆           ┆      ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘, 'damages': shape: (705, 27)
┌───────┬────────────┬────────────┬────────────┬───┬────────────┬─────────┬────────────┬───────────┐
│ armor ┆ attacker_X ┆ attacker_Y ┆ attacker_Z ┆ … ┆ victim_sid ┆ weapon  ┆ dmg_health ┆ round_num │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ e          ┆ ---     ┆ _real      ┆ ---       │
│ i32   ┆ f32        ┆ f32        ┆ f32        ┆   ┆ ---        ┆ str     ┆ ---        ┆ u32       │
│       ┆            ┆            ┆            ┆   ┆ str        ┆         ┆ i32        ┆           │
╞═══════╪════════════╪════════════╪════════════╪═══╪════════════╪═════════╪════════════╪═══════════╡
│ 99    ┆ -942.51043 ┆ -3631.3640 ┆ -35.157288 ┆ … ┆ t          ┆ knife   ┆ 13         ┆ 1         │
│       ┆ 7          ┆ 14         ┆            ┆   ┆            ┆         ┆            ┆           │
│ 0     ┆ -208.50366 ┆ -2193.0471 ┆ -87.96875  ┆ … ┆ t          ┆ hkp2000 ┆ 100        ┆ 1         │
│       ┆ 2          ┆ 19         ┆            ┆   ┆            ┆         ┆            ┆           │
│ 93    ┆ -922.60870 ┆ -1653.8845 ┆ -86.027771 ┆ … ┆ t          ┆ hkp2000 ┆ 15         ┆ 1         │
│       ┆ 4          ┆ 21         ┆            ┆   ┆            ┆         ┆            ┆           │
│ 93    ┆ -409.54687 ┆ -2236.8854 ┆ -36.875    ┆ … ┆ ct         ┆ glock   ┆ 13         ┆ 1         │
│       ┆ 5          ┆ 98         ┆            ┆   ┆            ┆         ┆            ┆           │
│ 93    ┆ -915.77911 ┆ -1653.0316 ┆ -87.96875  ┆ … ┆ t          ┆ hkp2000 ┆ 84         ┆ 1         │
│       ┆ 4          ┆ 16         ┆            ┆   ┆            ┆         ┆            ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …       ┆ …          ┆ …         │
│ 100   ┆ -2829.3195 ┆ -987.73254 ┆ -31.96875  ┆ … ┆ ct         ┆ ak47    ┆ 26         ┆ 24        │
│       ┆ 8          ┆ 4          ┆            ┆   ┆            ┆         ┆            ┆           │
│ 95    ┆ -2821.6833 ┆ -990.10156 ┆ -31.96875  ┆ … ┆ ct         ┆ ak47    ┆ 34         ┆ 24        │
│       ┆ 5          ┆ 2          ┆            ┆   ┆            ┆         ┆            ┆           │
│ 99    ┆ -2742.3503 ┆ -748.82586 ┆ 15.493711  ┆ … ┆ t          ┆ aug     ┆ 31         ┆ 24        │
│       ┆ 42         ┆ 7          ┆            ┆   ┆            ┆         ┆            ┆           │
│ 91    ┆ -2807.6262 ┆ -991.89025 ┆ -31.96875  ┆ … ┆ ct         ┆ ak47    ┆ 27         ┆ 24        │
│       ┆ 21         ┆ 9          ┆            ┆   ┆            ┆         ┆            ┆           │
│ 87    ┆ -2807.6262 ┆ -991.89025 ┆ -31.96875  ┆ … ┆ ct         ┆ ak47    ┆ 12         ┆ 24        │
│       ┆ 21         ┆ 9          ┆            ┆   ┆            ┆         ┆            ┆           │
└───────┴────────────┴────────────┴────────────┴───┴────────────┴─────────┴────────────┴───────────┘, 'grenades': shape: (1_625_720, 9)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ thrower_st ┆ thrower    ┆ grenade_t ┆ tick   ┆ … ┆ Y         ┆ Z         ┆ entity_id ┆ round_num │
│ eamid      ┆ ---        ┆ ype       ┆ ---    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ ---        ┆ str        ┆ ---       ┆ i32    ┆   ┆ f32       ┆ f32       ┆ i32       ┆ u32       │
│ u64        ┆            ┆ str       ┆        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 7656119805 ┆ Captain    ┆ CDecoyGre ┆ 7888   ┆ … ┆ null      ┆ null      ┆ 577       ┆ 1         │
│ 1680113    ┆ Blake      ┆ nade      ┆        ┆   ┆           ┆           ┆           ┆           │
│ 7656119805 ┆ Captain    ┆ CDecoyGre ┆ 7889   ┆ … ┆ null      ┆ null      ┆ 577       ┆ 1         │
│ 1680113    ┆ Blake      ┆ nade      ┆        ┆   ┆           ┆           ┆           ┆           │
│ 7656119805 ┆ Captain    ┆ CDecoyGre ┆ 7890   ┆ … ┆ null      ┆ null      ┆ 577       ┆ 1         │
│ 1680113    ┆ Blake      ┆ nade      ┆        ┆   ┆           ┆           ┆           ┆           │
│ 7656119805 ┆ Captain    ┆ CDecoyGre ┆ 7891   ┆ … ┆ null      ┆ null      ┆ 577       ┆ 1         │
│ 1680113    ┆ Blake      ┆ nade      ┆        ┆   ┆           ┆           ┆           ┆           │
│ 7656119805 ┆ Captain    ┆ CDecoyGre ┆ 7892   ┆ … ┆ null      ┆ null      ┆ 577       ┆ 1         │
│ 1680113    ┆ Blake      ┆ nade      ┆        ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …         ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 7656119800 ┆ blu        ┆ CFlashban ┆ 162267 ┆ … ┆ null      ┆ null      ┆ 622       ┆ 24        │
│ 4039473    ┆            ┆ g         ┆        ┆   ┆           ┆           ┆           ┆           │
│ 7656119798 ┆ Tundra ツ  ┆ CHEGrenad ┆ 162267 ┆ … ┆ null      ┆ null      ┆ 629       ┆ 24        │
│ 7271352    ┆            ┆ e         ┆        ┆   ┆           ┆           ┆           ┆           │
│ 7656119800 ┆ blu        ┆ CMolotovG ┆ 162267 ┆ … ┆ null      ┆ null      ┆ 643       ┆ 24        │
│ 4039473    ┆            ┆ renade    ┆        ┆   ┆           ┆           ┆           ┆           │
│ 7656119804 ┆ KeTaNoS    ┆ CSmokeGre ┆ 162267 ┆ … ┆ -2767.406 ┆ -85.96875 ┆ 728       ┆ 24        │
│ 5998047    ┆            ┆ nadeProje ┆        ┆   ┆ 25        ┆           ┆           ┆           │
│            ┆            ┆ ctile     ┆        ┆   ┆           ┆           ┆           ┆           │
│ 7656119797 ┆ Dude       ┆ CFlashban ┆ 162267 ┆ … ┆ null      ┆ null      ┆ 963       ┆ 24        │
│ 0397706    ┆            ┆ g         ┆        ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘, 'shots': shape: (3_485, 14)
┌─────────┬──────────┬────────┬────────┬───┬──────────────┬─────────────┬──────────────┬───────────┐
│ ct_side ┆ silenced ┆ t_side ┆ tick   ┆ … ┆ player_steam ┆ player_side ┆ weapon       ┆ round_num │
│ ---     ┆ ---      ┆ ---    ┆ ---    ┆   ┆ id           ┆ ---         ┆ ---          ┆ ---       │
│ str     ┆ bool     ┆ str    ┆ i32    ┆   ┆ ---          ┆ str         ┆ str          ┆ u32       │
│         ┆          ┆        ┆        ┆   ┆ u64          ┆             ┆              ┆           │
╞═════════╪══════════╪════════╪════════╪═══╪══════════════╪═════════════╪══════════════╪═══════════╡
│ ct      ┆ false    ┆ t      ┆ 8112   ┆ … ┆ 765611980341 ┆ t           ┆ weapon_decoy ┆ 1         │
│         ┆          ┆        ┆        ┆   ┆ 61077        ┆             ┆              ┆           │
│ ct      ┆ false    ┆ t      ┆ 8234   ┆ … ┆ 765611983545 ┆ ct          ┆ weapon_knife ┆ 1         │
│         ┆          ┆        ┆        ┆   ┆ 78034        ┆             ┆              ┆           │
│ ct      ┆ false    ┆ t      ┆ 8884   ┆ … ┆ 765611980107 ┆ t           ┆ weapon_knife ┆ 1         │
│         ┆          ┆        ┆        ┆   ┆ 96900        ┆             ┆ _stiletto    ┆           │
│ ct      ┆ true     ┆ t      ┆ 9146   ┆ … ┆ 765611980040 ┆ ct          ┆ weapon_usp_s ┆ 1         │
│         ┆          ┆        ┆        ┆   ┆ 39473        ┆             ┆ ilencer      ┆           │
│ ct      ┆ false    ┆ t      ┆ 9193   ┆ … ┆ 765611980341 ┆ t           ┆ weapon_glock ┆ 1         │
│         ┆          ┆        ┆        ┆   ┆ 61077        ┆             ┆              ┆           │
│ …       ┆ …        ┆ …      ┆ …      ┆ … ┆ …            ┆ …           ┆ …            ┆ …         │
│ ct      ┆ false    ┆ t      ┆ 162256 ┆ … ┆ 765611982409 ┆ ct          ┆ weapon_aug   ┆ 24        │
│         ┆          ┆        ┆        ┆   ┆ 03150        ┆             ┆              ┆           │
│ ct      ┆ false    ┆ t      ┆ 162256 ┆ … ┆ 765611979703 ┆ t           ┆ weapon_ak47  ┆ 24        │
│         ┆          ┆        ┆        ┆   ┆ 97706        ┆             ┆              ┆           │
│ ct      ┆ false    ┆ t      ┆ 162262 ┆ … ┆ 765611982409 ┆ ct          ┆ weapon_aug   ┆ 24        │
│         ┆          ┆        ┆        ┆   ┆ 03150        ┆             ┆              ┆           │
│ ct      ┆ false    ┆ t      ┆ 162262 ┆ … ┆ 765611979703 ┆ t           ┆ weapon_ak47  ┆ 24        │
│         ┆          ┆        ┆        ┆   ┆ 97706        ┆             ┆              ┆           │
│ ct      ┆ false    ┆ t      ┆ 162268 ┆ … ┆ 765611979703 ┆ t           ┆ weapon_ak47  ┆ 24        │
│         ┆          ┆        ┆        ┆   ┆ 97706        ┆             ┆              ┆           │
└─────────┴──────────┴────────┴────────┴───┴──────────────┴─────────────┴──────────────┴───────────┘, 'footsteps': shape: (17_752, 15)
┌─────────┬──────────┬────────┬───────┬───┬─────────────┬────────────────┬─────────────┬───────────┐
│ ct_side ┆ duration ┆ radius ┆ step  ┆ … ┆ player_name ┆ player_steamid ┆ player_side ┆ round_num │
│ ---     ┆ ---      ┆ ---    ┆ ---   ┆   ┆ ---         ┆ ---            ┆ ---         ┆ ---       │
│ str     ┆ f32      ┆ i32    ┆ bool  ┆   ┆ str         ┆ u64            ┆ str         ┆ u32       │
╞═════════╪══════════╪════════╪═══════╪═══╪═════════════╪════════════════╪═════════════╪═══════════╡
│ ct      ┆ 0.1      ┆ 1100   ┆ false ┆ … ┆ Dude        ┆ 76561197970397 ┆ ct          ┆ 1         │
│         ┆          ┆        ┆       ┆   ┆             ┆ 706            ┆             ┆           │
│ ct      ┆ 0.1      ┆ 1100   ┆ false ┆ … ┆ Dude        ┆ 76561197970397 ┆ ct          ┆ 1         │
│         ┆          ┆        ┆       ┆   ┆             ┆ 706            ┆             ┆           │
│ ct      ┆ 0.1      ┆ 1100   ┆ false ┆ … ┆ Tundra ツ   ┆ 76561197987271 ┆ ct          ┆ 1         │
│         ┆          ┆        ┆       ┆   ┆             ┆ 352            ┆             ┆           │
│ ct      ┆ 0.1      ┆ 1100   ┆ false ┆ … ┆ Tundra ツ   ┆ 76561197987271 ┆ ct          ┆ 1         │
│         ┆          ┆        ┆       ┆   ┆             ┆ 352            ┆             ┆           │
│ ct      ┆ 0.1      ┆ 1100   ┆ false ┆ … ┆ blu         ┆ 76561198004039 ┆ ct          ┆ 1         │
│         ┆          ┆        ┆       ┆   ┆             ┆ 473            ┆             ┆           │
│ …       ┆ …        ┆ …      ┆ …     ┆ … ┆ …           ┆ …              ┆ …           ┆ …         │
│ ct      ┆ 0.5      ┆ 1100   ┆ true  ┆ … ┆ Tundra ツ   ┆ 76561197987271 ┆ t           ┆ 24        │
│         ┆          ┆        ┆       ┆   ┆             ┆ 352            ┆             ┆           │
│ ct      ┆ 0.1      ┆ 1400   ┆ false ┆ … ┆ Dottersack  ┆ 76561198240903 ┆ ct          ┆ 24        │
│         ┆          ┆        ┆       ┆   ┆             ┆ 150            ┆             ┆           │
│ ct      ┆ 0.1      ┆ 1070   ┆ false ┆ … ┆ Dottersack  ┆ 76561198240903 ┆ ct          ┆ 24        │
│         ┆          ┆        ┆       ┆   ┆             ┆ 150            ┆             ┆           │
│ ct      ┆ 0.1      ┆ 1070   ┆ false ┆ … ┆ Dottersack  ┆ 76561198240903 ┆ ct          ┆ 24        │
│         ┆          ┆        ┆       ┆   ┆             ┆ 150            ┆             ┆           │
│ ct      ┆ 0.1      ┆ 1065   ┆ false ┆ … ┆ Dottersack  ┆ 76561198240903 ┆ ct          ┆ 24        │
│         ┆          ┆        ┆       ┆   ┆             ┆ 150            ┆             ┆           │
└─────────┴──────────┴────────┴───────┴───┴─────────────┴────────────────┴─────────────┴───────────┘, 'smokes': shape: (105, 15)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ entity_id ┆ start_tic ┆ end_tick ┆ thrower_X ┆ … ┆ X         ┆ Y         ┆ Z         ┆ round_num │
│ ---       ┆ k         ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64       ┆ ---       ┆ i64      ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ u32       │
│           ┆ i64       ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 724       ┆ 11783     ┆ 13195    ┆ -2241.837 ┆ … ┆ -2910.173 ┆ -3099.728 ┆ 12.750005 ┆ 2         │
│           ┆           ┆          ┆ 646       ┆   ┆ 584       ┆ 271       ┆           ┆           │
│ 454       ┆ 11794     ┆ 13206    ┆ -565.2964 ┆ … ┆ -477.7250 ┆ -2759.731 ┆ -85.96875 ┆ 2         │
│           ┆           ┆          ┆ 48        ┆   ┆ 06        ┆ 934       ┆           ┆           │
│ 902       ┆ 11800     ┆ 13212    ┆ -3462.892 ┆ … ┆ -3623.036 ┆ -2416.142 ┆ 10.03125  ┆ 2         │
│           ┆           ┆          ┆ 334       ┆   ┆ 865       ┆ 578       ┆           ┆           │
│ 17        ┆ 20748     ┆ 22160    ┆ -627.0956 ┆ … ┆ -457.9971 ┆ -2639.520 ┆ -85.96875 ┆ 3         │
│           ┆           ┆          ┆ 42        ┆   ┆ 31        ┆ 752       ┆           ┆           │
│ 441       ┆ 20814     ┆ 22226    ┆ -3589.993 ┆ … ┆ -3558.339 ┆ -2487.396 ┆ 10.03125  ┆ 3         │
│           ┆           ┆          ┆ 652       ┆   ┆ 844       ┆ 24        ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 364       ┆ 160150    ┆ 161562   ┆ -2425.396 ┆ … ┆ -2728.074 ┆ -3157.313 ┆ 19.61228  ┆ 24        │
│           ┆           ┆          ┆ 729       ┆   ┆ 463       ┆ 477       ┆           ┆           │
│ 84        ┆ 160505    ┆ 161917   ┆ -2456.225 ┆ … ┆ -2298.696 ┆ -2075.744 ┆ 10.031256 ┆ 24        │
│           ┆           ┆          ┆ 83        ┆   ┆ 777       ┆ 629       ┆           ┆           │
│ 575       ┆ 160941    ┆ 162353   ┆ -3322.755 ┆ … ┆ -3711.378 ┆ -1379.647 ┆ -90.57803 ┆ 24        │
│           ┆           ┆          ┆ 371       ┆   ┆ 418       ┆ 339       ┆ 3         ┆           │
│ 728       ┆ 161201    ┆ 162613   ┆ -957.8494 ┆ … ┆ -427.7510 ┆ -2767.418 ┆ -85.96875 ┆ 24        │
│           ┆           ┆          ┆ 87        ┆   ┆ 07        ┆ 457       ┆           ┆           │
│ 592       ┆ 161638    ┆ 163050   ┆ -3498.416 ┆ … ┆ -3773.078 ┆ -2515.978 ┆ 10.03125  ┆ 24        │
│           ┆           ┆          ┆ 26        ┆   ┆ 613       ┆ 271       ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘, 'infernos': shape: (27, 15)

In [5]:
def build_player_index(data):
    df = data["player_round_totals"]

    players = (
        df
        .filter(df["side"] == "all")
        .unique(subset=["steamid"])
    )

    print("[Players]", players.height)
    display(players)

    return players


players = build_player_index(data)

[Players] 10

shape: (10, 4)
┌───────────────┬───────────────────┬──────┬──────────┐
│ name          ┆ steamid           ┆ side ┆ n_rounds │
│ ---           ┆ ---               ┆ ---  ┆ ---      │
│ str           ┆ u64               ┆ str  ┆ u32      │
╞═══════════════╪═══════════════════╪══════╪══════════╡
│ blu           ┆ 76561198004039473 ┆ all  ┆ 24       │
│ Couchyyy1337  ┆ 76561198034161077 ┆ all  ┆ 24       │
│ Soulcrusher   ┆ 76561198354578034 ┆ all  ┆ 24       │
│ Dottersack    ┆ 76561198240903150 ┆ all  ┆ 24       │
│ Tundra ツ     ┆ 76561197987271352 ┆ all  ┆ 24       │
│ Captain Blake ┆ 76561198051680113 ┆ all  ┆ 24       │
│ -Zuria-       ┆ 76561198010796900 ┆ all  ┆ 24       │
│ KeTaNoS       ┆ 76561198045998047 ┆ all  ┆ 24       │
│ Dude          ┆ 76561197970397706 ┆ all  ┆ 24       │
│ Sindilia      ┆ 76561198095760902 ┆ all  ┆ 24       │
└───────────────┴───────────────────┴──────┴──────────┘

In [18]:
import polars as pl

def build_player_stats(data):
    print("[Stats] Building...")

    # --- SOURCE TABLES ---
    kills = data["kills"]
    damages = data["damages"]
    shots = data["shots"]
    rounds = data["rounds"]
    players_df = data["player_round_totals"]

    # --- PLAYER INDEX (clean + unique) ---
    players = (
        players_df
        .filter(pl.col("side") == "all")
        .select(["steamid", "name"])
        .unique(subset=["steamid"])
    )

    # --- NORMALIZE EVENTS ---
    kills_norm = kills.select([
        pl.col("attacker_steamid").alias("steamid"),
        pl.lit(1).alias("kills"),
        pl.lit(0).alias("deaths"),
        pl.lit(0).alias("damage"),
        pl.lit(0).alias("shots"),
    ])

    deaths_norm = kills.select([
        pl.col("victim_steamid").alias("steamid"),
        pl.lit(0).alias("kills"),
        pl.lit(1).alias("deaths"),
        pl.lit(0).alias("damage"),
        pl.lit(0).alias("shots"),
    ])

    damage_norm = damages.select([
        pl.col("attacker_steamid").alias("steamid"),
        pl.lit(0).alias("kills"),
        pl.lit(0).alias("deaths"),
        pl.col("dmg_health_real").alias("damage"),
        pl.lit(0).alias("shots"),
    ])

    shots_norm = shots.select([
        pl.col("player_steamid").alias("steamid"),
        pl.lit(0).alias("kills"),
        pl.lit(0).alias("deaths"),
        pl.lit(0).alias("damage"),
        pl.lit(1).alias("shots"),
    ])

    # --- CONCAT EVENTS ---
    all_events = pl.concat([
        kills_norm,
        deaths_norm,
        damage_norm,
        shots_norm
    ])

    # --- AGGREGATE ---
    stats = (
        all_events
        .group_by("steamid")
        .agg([
            pl.sum("kills"),
            pl.sum("deaths"),
            pl.sum("damage"),
            pl.sum("shots"),
        ])
    )

    # --- DERIVED METRICS ---
    n_rounds = rounds.height

    stats = stats.with_columns([
        (pl.col("kills") / pl.when(pl.col("deaths") == 0).then(1).otherwise(pl.col("deaths"))).alias("kd"),
        (pl.col("damage") / n_rounds).alias("adr"),
        (pl.col("kills") / pl.when(pl.col("shots") == 0).then(1).otherwise(pl.col("shots"))).alias("accuracy")
    ])

    # --- JOIN PLAYER NAMES ---
    stats = stats.join(players, on="steamid", how="left")

    # --- COLUMN ORDER ---
    stats = stats.select([
        "steamid",
        "name",
        "kills",
        "deaths",
        "damage",
        "shots",
        "kd",
        "adr",
        "accuracy",
    ])

    # --- SORT ---
    stats = stats.sort("kills", descending=True)

    print(f"[Players] {players.height}")
    print("[Stats] Done")

    display(stats)

    return stats


player_stats = build_player_stats(data)

[Stats] Building...
[Players] 10
[Stats] Done

shape: (11, 9)
┌──────────────────┬───────────────┬───────┬────────┬───┬───────┬──────────┬────────────┬──────────┐
│ steamid          ┆ name          ┆ kills ┆ deaths ┆ … ┆ shots ┆ kd       ┆ adr        ┆ accuracy │
│ ---              ┆ ---           ┆ ---   ┆ ---    ┆   ┆ ---   ┆ ---      ┆ ---        ┆ ---      │
│ u64              ┆ str           ┆ i32   ┆ i32    ┆   ┆ i32   ┆ f64      ┆ f64        ┆ f64      │
╞══════════════════╪═══════════════╪═══════╪════════╪═══╪═══════╪══════════╪════════════╪══════════╡
│ 7656119800403947 ┆ blu           ┆ 31    ┆ 15     ┆ … ┆ 466   ┆ 2.066667 ┆ 124.833333 ┆ 0.066524 │
│ 3                ┆               ┆       ┆        ┆   ┆       ┆          ┆            ┆          │
│ 7656119804599804 ┆ KeTaNoS       ┆ 29    ┆ 16     ┆ … ┆ 382   ┆ 1.8125   ┆ 111.083333 ┆ 0.075916 │
│ 7                ┆               ┆       ┆        ┆   ┆       ┆          ┆            ┆          │
│ 7656119798727135 ┆ Tundra ツ     ┆ 21    ┆ 15     ┆ … ┆ 427   ┆ 1.4      ┆ 78.208333  ┆ 0.04918  │
│ 2                ┆               ┆       ┆        ┆   ┆       ┆          ┆            ┆          │
│ 7656119809576090 ┆ Sindilia      ┆ 20    ┆ 19     ┆ … ┆ 309   ┆ 1.052632 ┆ 108.875    ┆ 0.064725 │
│ 2                ┆               ┆       ┆        ┆   ┆       ┆          ┆            ┆          │
│ 7656119805168011 ┆ Captain Blake ┆ 16    ┆ 20     ┆ … ┆ 264   ┆ 0.8      ┆ 64.833333  ┆ 0.060606 │
│ 3                ┆               ┆       ┆        ┆   ┆       ┆          ┆            ┆          │
│ …                ┆ …             ┆ …     ┆ …      ┆ … ┆ …     ┆ …        ┆ …          ┆ …        │
│ 7656119835457803 ┆ Soulcrusher   ┆ 14    ┆ 18     ┆ … ┆ 375   ┆ 0.777778 ┆ 56.458333  ┆ 0.037333 │
│ 4                ┆               ┆       ┆        ┆   ┆       ┆          ┆            ┆          │
│ 7656119803416107 ┆ Couchyyy1337  ┆ 14    ┆ 20     ┆ … ┆ 419   ┆ 0.7      ┆ 81.541667  ┆ 0.033413 │
│ 7                ┆               ┆       ┆        ┆   ┆       ┆          ┆            ┆          │
│ 7656119801079690 ┆ -Zuria-       ┆ 10    ┆ 21     ┆ … ┆ 408   ┆ 0.47619  ┆ 57.666667  ┆ 0.02451  │
│ 0                ┆               ┆       ┆        ┆   ┆       ┆          ┆            ┆          │
│ 7656119797039770 ┆ Dude          ┆ 9     ┆ 18     ┆ … ┆ 189   ┆ 0.5      ┆ 47.958333  ┆ 0.047619 │
│ 6                ┆               ┆       ┆        ┆   ┆       ┆          ┆            ┆          │
│ null             ┆ null          ┆ 1     ┆ 0      ┆ … ┆ 0     ┆ 1.0      ┆ 4.25       ┆ 1.0      │
└──────────────────┴───────────────┴───────┴────────┴───┴───────┴──────────┴────────────┴──────────┘